' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Hono" {
  [Hono App]
  [Middleware \nrolesAllowed()]
  [Router / Handler]

  [Yoga Server]
  [Resolver / Handler]

  [AppProfileService]

  [PrismaClient]

  [MailService]
}


cloud {
    [Prisma]
}

cloud {
    [jose \nissuer]
}

cloud {
    [nodemailer]
}

database "DB reclaim" {
    [Tabelle \napp_profile]
    [Tabelle \ntracking_config]
    [Tabelle \nscreentime_logs]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [Hono App]
[Hono App] ..> [Middleware \nrolesAllowed()]
[MailService] ~[hidden]~> [jose \nissuer]
[Middleware \nrolesAllowed()] ~~> [jose \nissuer]
[Middleware \nrolesAllowed()] ..> [Router / Handler]
[Router / Handler] ..> [AppProfileService]

GraphQLClient ~~> [Hono App]
[Hono App] ..> [Yoga Server]
[Yoga Server] ..> [Resolver / Handler]
[Resolver / Handler] ..> [AppProfileService]
[Resolver / Handler] ~~> [jose \nissuer]

[AppProfileService] ..> [PrismaClient]

[PrismaClient] ~~> [Prisma]
[Prisma] ~~> [Tabelle \nbuch]
[Prisma] ~~> [Tabelle \ntitel]
[Prisma] ~~> [Tabelle \nabbildung]

[jose \nissuer] ~~> [Keycloak]

[AppProfileService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

footer (c) Nikolas Vix

@enduml
